# webpack.yml
mode: production

entry: ./lib/index.ts

output:
  path: dist
  filename: index.js
  library:
    type: module
  clean: true

experiments:
  outputModule: true

resolve:
  extensions:
    - .ts
    - .js
    - .json

module:
  rules:
    - test: /\.ts$/
      use: ts-loader
      exclude: /node_modules/

externals:
  fs: commonjs fs
  path: commonjs path
  crypto: commonjs crypto

target: node16

devtool: source-map

optimization:
  minimize: true

stats: minimal
*

